### ISSUE TITLE
NPE crash - Incompatibility Between Angel of Vengeance and Millenaire

### ISSUE THREAD

**Issue by Schadrach** [Tamaized/AoV#101]
If running both Millenaire and Angel of Vengeance, when an Astrologer (haven't tested with other classes yet), looking at a Millenaire villager causes a crash, exception is as follows:

[23:03:31] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Post@30ac20c:
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:426) ~[bzf.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128) ~[bmx.class:?]
	at tamaized.aov.client.gui.AoVOverlay.renderTarget(AoVOverlay.java:443) ~[AoVOverlay.class:?]
	at tamaized.aov.client.gui.AoVOverlay.renderOverlayPost(AoVOverlay.java:195) ~[AoVOverlay.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1461_AoVOverlay_renderOverlayPost_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:609) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:169) [GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at org.millenaire.common.entity.MillVillager.getConfig(MillVillager.java:1385) ~[MillVillager.class:?]
	at org.millenaire.common.entity.MillVillager.func_184582_a(MillVillager.java:1553) ~[MillVillager.class:?]
	at me.desht.pneumaticcraft.client.ClientEventHandler.setRenderHead(ClientEventHandler.java:167) ~[ClientEventHandler.class:?]
	at me.desht.pneumaticcraft.client.ClientEventHandler.onLivingRender(ClientEventHandler.java:158) ~[ClientEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2275_ClientEventHandler_onLivingRender_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) ~[caf.class:?]
	at org.millenaire.client.render.RenderMillVillager.doRender(RenderMillVillager.java:199) ~[RenderMillVillager.class:?]
	at org.millenaire.client.render.RenderMillVillager.func_76986_a(RenderMillVillager.java:48) ~[RenderMillVillager.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) ~[bzf.class:?]
	... 19 more

Reporting this issue to both mods.

**Comment by Tamaized** [comment]
Post the full log and upload it to https://gist.github.com

**Comment by Tamaized** [comment]
Issue is their end:
`NPE -> org.millenaire.common.entity.MillVillager.getConfig(MillVillager.java:1385)`
