### ISSUE TITLE
Server exception on player join in PolymorphCapabilityHandler

### ISSUE THREAD

**Issue by CplPibald** [Tamaized/AoV#102]
Dedicated MP server 
AoV-1.12-0.10.1
forge-1.12.2-14.23.5.2768

Upgraded AoV from 0.9.5 to 0.10.1.  Players are unable to join server.  On attempt to join, player gets a network error, and server log contains the following exception.  Server does not crash.

```
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@6dcef3d6:
java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
        at tamaized.aov.common.capabilities.polymorph.PolymorphCapabilityHandler.update(PolymorphCapabilityHandler.java:179) ~[PolymorphCapabilityHandler.class:?]
        at tamaized.aov.common.events.TickHandler.update(TickHandler.java:82) ~[TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_956_TickHandler_update_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Tamaized** [comment]
Update Forge to 2779 or higher

**Comment by Tamaized** [comment]
Reopening for myself as a note to bump the Forge dependency version
