### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by reallyrealboy** [Tamaized/AoV#126]
whenever I try to create a new world with the latest 1.12.2 version of the mod (with the latest dependency mod) it crashes saying " The game crashed whilst ticking player"
here is the full crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/6/19 7:25 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at tamaized.aov.common.capabilities.polymorph.PolymorphCapabilityHandler.update(PolymorphCapabilityHandler.java:183)
	at tamaized.aov.common.events.TickHandler.update(TickHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_TickHandler_update_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at tamaized.aov.common.capabilities.polymorph.PolymorphCapabilityHandler.update(PolymorphCapabilityHandler.java:183)
	at tamaized.aov.common.events.TickHandler.update(TickHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_TickHandler_update_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 465
	Entity Name: realyrealboy
	Entity's Exact location: 237.50, 75.00, 11.50
	Entity's Block location: World: (237,75,11), Chunk: (at 13,4,11 in 14,0; contains blocks 224,0,0 to 239,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@144d895d
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252875968 bytes (241 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | tammodized | 0.15.6       | TamModized-1.12.2-0.15.6 (2).jar | None                                     |
	| UCHIJAAAA | aov        | 0.11.3       | AoV-1.12-0.11.3.jar              | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['realyrealboy'/465, l='New World', x=237.50, y=75.00, z=11.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tamaized** [comment]
Duplicate #102

**Comment by Tamaized** [comment]
0.11.3 is not the latest 1.12.2 version, 0.11.4 is
