### ISSUE TITLE
1.13.2 crash

### ISSUE THREAD

**Issue by reallyrealboy** [Tamaized/AoV#127]
whenever I try to make a new world with aov latest download it crashes

crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 4/6/19 8:37 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.remapName(Ljava/lang/String;)Ljava/lang/String;
	at tamaized.aov.common.helper.UtilHelper.findField(UtilHelper.java:20)
	at tamaized.aov.common.capabilities.polymorph.PolymorphCapabilityHandler.update(PolymorphCapabilityHandler.java:183)
	at tamaized.aov.common.events.TickHandler.update(TickHandler.java:138)
	at net.minecraftforge.eventbus.ASMEventHandler_13_TickHandler_update_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:100)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:266)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:350)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:178)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at tamaized.aov.common.helper.UtilHelper.findField(UtilHelper.java:20)
	at tamaized.aov.common.capabilities.polymorph.PolymorphCapabilityHandler.update(PolymorphCapabilityHandler.java:183)
	at tamaized.aov.common.events.TickHandler.update(TickHandler.java:138)
	at net.minecraftforge.eventbus.ASMEventHandler_13_TickHandler_update_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:100)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:266)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 326
	Entity Name: realyrealboy
	Entity's Exact location: -200.50, 69.00, 22.50
	Entity's Block location: World: (-201,69,22), Chunk: (at 7,4,6 in -13,1; contains blocks -208,0,16 to -193,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:350)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:178)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2f296ab7
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 242459904 bytes (231 MB) / 637534208 bytes (608 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['realyrealboy'/326, l='New World', x=-200.50, y=69.00, z=22.50]]
	Data Packs: vanilla, mod:forge, mod:aov (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Tamaized** [comment]
Could you upload crash-reports/logs here from now on: https://gist.github.com
Then include the link to the gist in the issue. Makes it easier for me and other devs.

**Comment by reallyrealboy** [comment]
what is a gist

**Comment by Tamaized** [comment]
It's the link i provided.

**Comment by reallyrealboy** [comment]
like this
https://gist.github.com/reallyrealboy/685d631225cbeb6fef4b3437b9ea30f0

**Comment by Tamaized** [comment]
Yep, perfect
