### ISSUE TITLE
AoV 0.7.2 crashes when examining for coremod candidacy

### ISSUE THREAD

**Issue by Knito58** [Tamaized/AoV#34]
MC 1.12.2, Forge 14.23.0.2515, AoV 0.7.2
Error happens in the Launcher. Going back to 0.6.2 fixes this one.
Log is in fml-client-latest.log.

...
[08:09:17] [main/DEBUG] [FML/]: Examining for coremod candidacy ActuallyAdditions-1.12.2-r124.jar
[08:09:17] [main/DEBUG] [FML/]: Not found coremod data in ActuallyAdditions-1.12.2-r124.jar
[08:09:17] [main/DEBUG] [FML/]: Examining for coremod candidacy advInv-1.12.1-1.4.2.jar
[08:09:17] [main/DEBUG] [FML/]: Not found coremod data in advInv-1.12.1-1.4.2.jar
[08:09:17] [main/DEBUG] [FML/]: Examining for coremod candidacy AoV-1.12.1-0.7.2.jar
[08:09:17] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\minecraft\1.12.2\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:104) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:75) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:38) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:137) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_25]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:1.8.0_25]
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456) ~[guava-21.0.jar:?]
	at com.google.common.io.CharSource.read(CharSource.java:232) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer.addJar(ModAccessTransformer.java:73) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:362) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:254) ~[forge-1.12.2-14.23.0.2515.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100) ~[forge-1.12.2-14.23.0.2515.jar:?]
	... 5 more
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:09:17] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Tamaized** [comment]
Does this only happen in 1.12.2?

**Comment by Tamaized** [comment]
Nevermind, it'll crash any version, I actually don't know why this is happening but i'm looking into it

**Comment by Tamaized** [comment]
fixed in 9a55e5ca4bba1ee4ae089f3a7e6337af53073804

**Comment by Knito58** [comment]
Sorry. Couldn't answer - was at work. Thank you for fixing this. The new GUI looks great.
